
// ALERT
// ALERT DIGUNAKAN UNTUK MEMUNCULKAN POP UP DALAM BROWSER

// alert('nama kamu siapa?');

// PROMPT
// PROMPT DIGUNAKAN UNTUK MENIMBULKAN POP UP YANG DAPAT KITA MASUKKAN SUATU INPUT

// prompt('umur kamu berapa?');

// PROMPT BISA DIKOMBINASIKAN DENGAN VARIABEL, FUNGSINYA AGAR NILAI YANG DIINPUT PADA PROMPT MASUK KE DALAM SUATU VARIABEL


// APABILA KITA MENGINPUT SESUATU KEDALAM PROMPT TERSEBUT, MAKA SESUATU YANG DIINPUT AKAN MASUK KE VARIABEL NAMA DAN DAPAT DIGUNAKAN UNTUK COMMAND SETELAHNYA
// var nama = prompt('nama kamu siapa?');

// alert ('nama kamu ' + nama);

// CONFIRM
// CONFIRM DIGUNAKAN UNTUK MENDAPATKAN KONFIRMASI DARI USER, KONFIRM BISA DIKOMBINASIKAN DENGAN SUATU KONDISI ATAU EVENT YANG AKAN TERJADI JIKA KITA MENGKLIK SUATU TOMBOLA YANG ADA DALAM CONFIRM TERSEBUT
// confirm('Apakah kamu yakin?');

// CONTOH
// var test = confirm('Apakah kamu yakin?');

// alert(test);

// CONTOH LAIN
var test = confirm('Apakah kamu yakin?')

if (test === true){
    alert('User menekan tombol OK')
}else {
    alert('User menekan tombol CANCEL')
};