// ARRAY
// ARRAY ADALAH TIPE DATA YANG DIGUNAKAN UNTUK MENDESKRIPSIKAN KUMPULAN ELEMEN (NILAI ATAU VARIABEL), YANG TIAP-TIAP ELEMENNYA MEMILIKI INDEX

// ARRAY
// VARIABEL JAMAK YANG MEMPUNYAI BANYAK ELEMEN DAN DIACU DENGAN NAMA YANG SAMA
// KUMPULAN PASANGAN KEY DAN NILAI / KEY AND VOLUME PAIR
// KEY ADALAH INDEX PADA ARRAY DENGAN TIPE INTEGER YANG DIMULAI DARI 0
// ARRAY PADA JAVASCRIPT BERTIPE OBJECT
// ARRAY PADA JAVASCRIPT MEMILIKI FUNGSI ATAU METHODE LENGTH UNTUK MENGHITUNG JUMLAH ELEMEN DI DALAMNYA
// ELEMEN PADA ARRAY BOLEH MEMILIKI TIPE DATA YANG BERBEDA
// ARRAY DILAMBANGKAN DENGAN []
// ARRAY BISA DIMASUKKAN KEDALAM ARRAY LAIN

var hari = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']
console.log(hari[4])

var integer = [1, 2, 3, 4, 5]
console.log(integer[2])

var mix = ['string', 1, true]
console.log(mix[2])

function myfunc(){
    return a+b
}

var arr1 = ['string', 1, true, myfunc]
console.log(arr1[3])

// ARRAY YANG MEMILIKI ARRAY DI DALAMNYA DISEBUT ARRAY MULTI DIMENSI
var arr2 = ['string', 1, true, myfunc, [1, 2, 3]]
console.log(arr2[4][1])

