
// ALLERT DIGUNAKAN UNTUK MEMUNCULKAN POP UP DALAM BROWSER

// alert('nama kamu siapa?')

// PROMPT DIGUNAKAN UNTUK MENIMBULKAN POP UP YANG DAPAT KITA MASUKKAN SUATU INPUT

// prompt('umur kamu berapa?')

// PROMPT BISA DIKOMBINASIKAN DENGAN VARIABEL, FUNGSINYA AGAR NILAI YANG DIINPUT PADA PROMPT MASUK KE DALAM SUATU VARIABEL


// APABILA KITA MENGINPUT SESUATU KEDALAM PROMPT TERSEBUT, MAKA SESUATU YANG DIINPUT AKAN MASUK KE VARIABEL NAMA DAN DAPAT DIGUNAKAN UNTUK COMMAND SETELAHNYA
var nama = prompt('nama kamu siapa?');

alert ('nama kamu ' + nama);